[package]
name = "rust_intrin"
version = "0.1.0"
authors = ["jack mott <jack.mott@gmail.com>"]

[lib]
bench = false

[dependencies]
rand = "*"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benchmarks"
harness = false