[package]
name = "rust_simd_tutorial"
version = "0.1.0"
authors = ["jack mott <jack.mott@gmail.com>"]
 

[dependencies]
rand = "*"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benchmarks"
harness = false